### ISSUE TITLE
Pause nor stops works

### ISSUE THREAD

**Issue by Nayar** [dplesca/omxremote#3]
Hi,

Using curl, i managed to play a song. However, pause or stop doesn't seem  to have any effect. I tried to manually launch omxplayer through CLI

```
pi@raspberrypi ~ $ mkfifo lolfifo
pi@raspberrypi ~ $ omxplayer Misunderstood-Lil\ Wayne-ykVwmYAUzEg.mp3 < lolfifo 
```

echoing "." in lolfifo will start playing. But any command after that doesn't seem to work.

**Comment by dplesca** [comment]
Hi, 

They seem to work for me. What happens here is something like this:

```bash
mkfifo lolfifo
omxplayer Misunderstood-Lil\ Wayne-ykVwmYAUzEg.mp3 < lolfifo 
echo . > lolfifo
echo -n p > lolfifo
echo -n q > lolfifo 
#any other commands
```
I've just tested it and it seems to work just fine, so I'm not sure what exactly may be the issue. The only difference is that I usually use as output the hdmi connection. 

On a side note if you want to play a music library I find much easier to do that using [mpd](http://www.musicpd.org/).

**Comment by Nayar** [comment]
Worked today. Guess my raspi needed a reboot. Sorry for inconvenience :)
